### ISSUE TITLE
Update 3D refinement command generated by gateway

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#11]
Hi @monaw - 

We need to make a few changes to the 3D refinement job. The 3D classification job works fine, and uploads the output results correctly (woohoo!). 

Could you remove these two parameters from both the gateway website and the command generated by the gateway for 3D refinement?  

Regularization parameter (tau2_fudge) 
Number of iterations (iter) 

And could you add this string to the generated 3D refinement command. This does not need any input from the user, and will also be used for every 3D refinement job: 

--split_random_halves

Thanks,
Mike

**Comment by monaw** [comment]
Ok done.  I checked the UI and it looks good but can't run a test.  Please let me know if the added parameter didn't show up.

**Comment by mcianfrocco** [comment]
Great ! Worked.
