### ISSUE TITLE
Should user account registration work at this point?

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#12]
Hi @monaw - just curious, are you logging into the gateway with an account? Or do you proceed as guest for now? 

Just wondering b/c I tried to create an account and the site just hung for a long time.

**Comment by monaw** [comment]
I have been using my account.  I just logged out and tried it as a guest with 2d classification and it worked fine...data uploaded, 2d job submitted and waiting to run.  It might be the gateway was being restarted after an update right when you were trying it?  Please try it again now as I think I've made all the updates you wanted and should be no more redeployment...

**Comment by monaw** [comment]
ok my guest run just finished successfully and result successfully transferred back to the gateway for viewing & download

**Comment by mcianfrocco** [comment]
Oh, ok, yes I was able to create an account. I think it must've been something with the gateway going up and down. 

Works now!
