### ISSUE TITLE
Gateway Help and How to Cite Us tabs need updating...

### ISSUE THREAD

**Issue by monaw** [leschzinerlab/COSMIC-CryoEM-Gateway#15]
Mike, do you want to keep those 2 tabs and what would you like to happen when user clicks on them?  CIPRES uses a static page.  Perhaps we can do the same and host the page off http://cosmic-cryoem.org?

**Comment by mcianfrocco** [comment]
@monaw - Yes, I'd like to keep both tabs, and I'll create pages off of cosmic-cryoem.org. I"ll send you the links soon so we can get them hooked in.

**Comment by mcianfrocco** [comment]
Hi @monaw - Could you update these links into the gateway: 

Help: https://cosmic-cryoem.org/gateway-help/

How to cite us: https://cosmic-cryoem.org/how-to-cite-cosmic/

**Comment by monaw** [comment]
Done.  It opens a new windows.  If you want a different behavior, let me know.

**Comment by mcianfrocco** [comment]
Great - looks good
