### ISSUE TITLE
Upload large 3D volume using web interface

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#3]
Goal: Try to upload very large 3D volume to see if web interface can handle the large size

**Comment by mcianfrocco** [comment]
@monaw  - try uploading this 3D volume that I put onto Comet. It is 442 MB and one of the biggest that I think we would need to deal with:

<pre>/projects/cosmic2/emd_8189.map</pre>

Details: 
- EMDB 8189
- 480 x 480 x 480 pixels
- 442 MB

**Comment by monaw** [comment]
Hmm, my upload test from was still going after 11 minutes...so this doesn't look like it will work...
