### ISSUE TITLE
Open Help link into new tab instead of new window

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#31]
Could we open the 'Help' link (in the main Cosmic2 toolbar) into a new tab instead of a new window? I think it would make it easier to interact with since the Help page will be an interactive website.

**Comment by mcianfrocco** [comment]
But we will leave the 'How to cite us' as a link that opens in a new window.

**Comment by monaw** [comment]
Ok, I've updated the javascript from popitup() to window.open().  This worked in my browser with my settings.  However, the behavior is browser-dependent and also depends on the user's settings so it is not guaranteed to open a tab in all browser.
