### ISSUE TITLE
What happens if a user provides files with the same name?

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#34]
Hi @cyoun - What happens if a user tries to upload another file that has the same name as a file/directory that is already on Comet? Does it get overwritten?

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , Yes, normally it is overwritten.

**Comment by mcianfrocco** [comment]
We are using synchronization with globus - that means if same file and same time stamp, then not overwritten. BUT, if differnet time stamps, then overwritten.
