### ISSUE TITLE
Add "Pending" and "Succeeded" into Globus transfer status

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#35]
Could we add Pending and Succeeded into the Globus transfer status page? While bytes transferred is helpful, it doesn't say how much is left to do.

**Comment by cdesyoun** [comment]
Hi @mcianfrocco , In transfer status page, there is "status" column, indicating the progress of the job task such as "ACTIVE", "INACTIVE", "SUCCESSDED", and "FAILED". 
And when looking into globus documentation (https://docs.globus.org/api/transfer/task/), it seems to me there is no attribute for checking the remaining byte size.
