### ISSUE TITLE
Change pixel size input to override reading from star file

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#5]
Instead of taking the input from the user, we should have the default value on the gateway be '-1', which means that we read the pixel size from the star file.

But, users could override this or provide it at this point.

**Comment by monaw** [comment]
The gateway now defaults to -1.  I presume valid answer to this parameter is either -1 or > 0.00?  Should this parameter be moved to the advanced section?  I did some tests and the validation of the values is working.  It is ready for your testing.

**Comment by mcianfrocco** [comment]
Great - this works as we want now. Thanks!
