### ISSUE TITLE
ntasks-per-node should be 24 not 15

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/COSMIC-CryoEM-Gateway#6]
@monaw - could you update the properties_dict file to have 24 ntasks-per-node ? Currently it is set at 15. 

Thanks,
Mike

**Comment by monaw** [comment]
Done for 3d classification and refine jobs.  I also set the nodes = 1.  There was a node_exclusive=1 which I removed.  Let me know if you want that back.  Gateway has been updated and ready for your testing.

**Comment by mcianfrocco** [comment]
Great! Thank you!
